FROM node:10.15.3

# Cleanup expired Let's Encrypt CA (Sept 30, 2021)
RUN sed -i '/^mozilla\/DST_Root_CA_X3/s/^/!/' /etc/ca-certificates.conf && update-ca-certificates -f

RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y libelf1 && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install --global yarn@1.3.2
