FROM node:9.5.0

RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y libelf1 && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install --global yarn@1.3.2
