name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set environment up
        run: |
          docker-compose build
          docker-compose run --rm -e MIX_ENV=test app mix do deps.get, deps.compile
          docker-compose run --rm webpack yarn install --no-progress

      - name: Run specs
        run: |
          docker-compose run --rm -e MIX_ENV=test app mix do compile --warnings-as-errors, ecto.create, ecto.load, test
          docker-compose run --rm webpack yarn test
          docker-compose run --rm webpack yarn webpack
          docker-compose run --rm webpack yarn flow check
          docker-compose run --rm webpack yarn eslint

  build:
    runs-on: ubuntu-latest
    needs: test
    if: contains('refs/heads/main', github.ref) || startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/preview') || startsWith(github.ref, 'refs/tags/')

    env:
      DOCKER_REPOSITORY: 'instedd/ask'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
      - uses: actions/checkout@v2
      - name: Build image & push to Docker Hub
        run: ./build.sh
