version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        compression algo gzip
        compression type text/html text/plain text/css application/javascript text/javascript
      port_rules:
      - hostname: ''
        path: /.well-known/acme-challenge
        priority: 1
        protocol: http
        service: letsencrypt/letsencrypt
        source_port: 80
        target_port: 80
      - hostname: '*.surveda-xx.org'
        path: ''
        priority: 8
        protocol: http
        service: redirect-to-https
        source_port: 80
        target_port: 80
      - hostname: surveda-xx.org
        path: ''
        priority: 9
        protocol: http
        service: redirect-to-https
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  redirect-to-https:
    scale: 1
    start_on_create: true
